services:
  - type: web
    name: sentinelai-node-service
    runtime: node
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health

  - type: web
    name: sentinelai-python-service
    runtime: python
    rootDir: server
    envVars:
      - key: PYTHONPATH
        value: ./app
    buildCommand: pip install -r app/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health